=== rafaykhanzada/CrystalReportWebAPI/CrystalReportWebAPI/Reports/ReportData/customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Customer_Query" minOccurs="0" maxOccurs="unbounded" />
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime" />
</xsd:complexType>
</xsd:element>
<xsd:element name="Customer_Query">
<xsd:annotation>
<xsd:appinfo />
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Customer_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
<xsd:element name="Customer_Credit_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
<xsd:element name="Customer_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="40" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Contact_First_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Contact_Last_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Contact_Title" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Contact_Position" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Last_Years_Sales" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double" />
<xsd:element name="Address1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="60" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Address2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="City" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Region" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Country" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Postal_Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="E-mail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Web_Site" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Phone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Fax" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20" />
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== rafaykhanzada/CrystalReportWebAPI/CrystalReportWebAPI/Reports/ReportData/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="customer.xsd" generated="2007-05-16T20:12:31">
<Customer_Query>
<Customer_ID>1</Customer_ID>
<Customer_Credit_ID>1</Customer_Credit_ID>
<Customer_Name>City Cyclists</Customer_Name>
<Contact_First_Name>Chris</Contact_First_Name>
<Contact_Last_Name>Christianson</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Sales Manager</Contact_Position>
<Last_Years_Sales>20045.2725</Last_Years_Sales>
<Address1>7464 South Kingsway</Address1>
<Address2>Suite 2006</Address2>
<City>Sterling Heights</City>
<Region>MI</Region>
<Country>USA</Country>
<Postal_Code>48358</Postal_Code>
<E-mail>Christianson@bba.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>810-939-6479</Phone>
<Fax>810-939-6602</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>2</Customer_ID>
<Customer_Credit_ID>2</Customer_Credit_ID>
<Customer_Name>Pathfinders</Customer_Name>
<Contact_First_Name>Christine</Contact_First_Name>
<Contact_Last_Name>Manley</Contact_Last_Name>
<Contact_Title>Miss</Contact_Title>
<Contact_Position>Sales Representative</Contact_Position>
<Last_Years_Sales>26369.63</Last_Years_Sales>
<Address1>410 Eighth Avenue</Address1>
<City>DeKalb</City>
<Region>IL</Region>
<Country>USA</Country>
<Postal_Code>60148</Postal_Code>
<E-mail>Manley@arubasport.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>815-756-9831</Phone>
<Fax>815-756-7536</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>3</Customer_ID>
<Customer_Credit_ID>3</Customer_Credit_ID>
<Customer_Name>Bike-A-Holics Anonymous</Customer_Name>
<Contact_First_Name>Gary</Contact_First_Name>
<Contact_Last_Name>Jannis</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Sales Associate</Contact_Position>
<Last_Years_Sales>4500</Last_Years_Sales>
<Address1>7429 Arbutus Boulevard</Address1>
<Address2>Suite 2017</Address2>
<City>Blacklick</City>
<Region>OH</Region>
<Country>USA</Country>
<Postal_Code>43005</Postal_Code>
<E-mail>Jannis@downunderbikes.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>614-759-9924</Phone>
<Fax>614-759-6343</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>4</Customer_ID>
<Customer_Credit_ID>4</Customer_Credit_ID>
<Customer_Name>Psycho-Cycle</Customer_Name>
<Contact_First_Name>Alexander</Contact_First_Name>
<Contact_Last_Name>Mast</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Sales Representative</Contact_Position>
<Last_Years_Sales>52809.105</Last_Years_Sales>
<Address1>8287 Scott Road</Address1>
<City>Huntsville</City>
<Region>AL</Region>
<Country>USA</Country>
<Postal_Code>35818</Postal_Code>
<E-mail>Mast@canbikes.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>205-430-0587</Phone>
<Fax>205-430-7737</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>5</Customer_ID>
<Customer_Credit_ID>5</Customer_Credit_ID>
<Customer_Name>Sporting Wheels Inc.</Customer_Name>
<Contact_First_Name>Patrick</Contact_First_Name>
<Contact_Last_Name>Reyess</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Sales Associate</Contact_Position>
<Last_Years_Sales>85642.56</Last_Years_Sales>
<Address1>480 Grant Way</Address1>
<Address2>Suite 1110</Address2>
<City>San Diego</City>
<Region>CA</Region>
<Country>USA</Country>
<Postal_Code>92150</Postal_Code>
<E-mail>Reyess@kangerootrikes.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>619-457-3186</Phone>
<Fax>619-457-9017</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>6</Customer_ID>
<Customer_Credit_ID>6</Customer_Credit_ID>
<Customer_Name>Rockshocks for Jocks</Customer_Name>
<Contact_First_Name>Heather</Contact_First_Name>
<Contact_Last_Name>Davis</Contact_Last_Name>
<Contact_Title>Ms.</Contact_Title>
<Contact_Position>Sales Representative</Contact_Position>
<Last_Years_Sales>40778.5225</Last_Years_Sales>
<Address1>1984 Sydney Street</Address1>
<City>Austin</City>
<Region>TX</Region>
<Country>USA</Country>
<Postal_Code>78770</Postal_Code>
<E-mail>Davis@brucebikes.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>512-349-7705</Phone>
<Fax>512-349-4983</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>7</Customer_ID>
<Customer_Credit_ID>7</Customer_Credit_ID>
<Customer_Name>Poser Cycles</Customer_Name>
<Contact_First_Name>Alex</Contact_First_Name>
<Contact_Last_Name>Smith</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Sales Agent</Contact_Position>
<Last_Years_Sales>10923</Last_Years_Sales>
<Address1>8194 Peter Avenue</Address1>
<City>Eden Prairie</City>
<Region>MN</Region>
<Country>USA</Country>
<Postal_Code>55360</Postal_Code>
<E-mail>Smith@peddlesofperth.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>612-947-4320</Phone>
<Fax>612-947-9422</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>8</Customer_ID>
<Customer_Credit_ID>8</Customer_Credit_ID>
<Customer_Name>Spokes &apos;N Wheels Ltd.</Customer_Name>
<Contact_First_Name>Kristina</Contact_First_Name>
<Contact_Last_Name>Chester</Contact_Last_Name>
<Contact_Title>Miss</Contact_Title>
<Contact_Position>Sales Representative</Contact_Position>
<Last_Years_Sales>25521.305</Last_Years_Sales>
<Address1>3802 Georgia Court</Address1>
<City>Des Moines</City>
<Region>IA</Region>
<Country>USA</Country>
<Postal_Code>50305</Postal_Code>
<E-mail>Chester@koalaroad.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>515-237-7769</Phone>
<Fax>515-237-9671</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>9</Customer_ID>
<Customer_Credit_ID>9</Customer_Credit_ID>
<Customer_Name>Trail Blazer&apos;s Place</Customer_Name>
<Contact_First_Name>Alexandra</Contact_First_Name>
<Contact_Last_Name>Burris</Contact_Last_Name>
<Contact_Title>Mrs.</Contact_Title>
<Contact_Position>Owner</Contact_Position>
<Last_Years_Sales>123658.46</Last_Years_Sales>
<Address1>6938 Beach Street</Address1>
<City>Madison</City>
<Region>WI</Region>
<Country>USA</Country>
<Postal_Code>53795</Postal_Code>
<E-mail>Burris@devilbikes.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>608-273-4883</Phone>
<Fax>608-273-0423</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>10</Customer_ID>
<Customer_Credit_ID>10</Customer_Credit_ID>
<Customer_Name>Rowdy Rims Company</Customer_Name>
<Contact_First_Name>Anthony</Contact_First_Name>
<Contact_Last_Name>Shoemaker</Contact_Last_Name>
<Contact_Title>Dr.</Contact_Title>
<Contact_Position>Sales Agent</Contact_Position>
<Last_Years_Sales>30131.455</Last_Years_Sales>
<Address1>4861 Second Road</Address1>
<City>Newbury Park</City>
<Region>CA</Region>
<Country>USA</Country>
<Postal_Code>91341</Postal_Code>
<E-mail>Shoemaker@piccolobike.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>805-375-0117</Phone>
<Fax>805-375-3533</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>11</Customer_ID>
<Customer_Credit_ID>11</Customer_Credit_ID>
<Customer_Name>Clean Air Transportation Co.</Customer_Name>
<Contact_First_Name>Bill</Contact_First_Name>
<Contact_Last_Name>Carter</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Sales Associate</Contact_Position>
<Last_Years_Sales>23789.245</Last_Years_Sales>
<Address1>1867 Thurlow Lane</Address1>
<Address2>Suite 1304</Address2>
<City>Conshohocken</City>
<Region>PA</Region>
<Country>USA</Country>
<Postal_Code>19453</Postal_Code>
<E-mail>Carter@BCS.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>610-941-5771</Phone>
<Fax>610-941-0216</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>12</Customer_ID>
<Customer_Credit_ID>12</Customer_Credit_ID>
<Customer_Name>Hooked on Helmets</Customer_Name>
<Contact_First_Name>Gerry</Contact_First_Name>
<Contact_Last_Name>Wade</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Owner</Contact_Position>
<Last_Years_Sales>52963.8225</Last_Years_Sales>
<Address1>7655 Mayberry Crescent</Address1>
<Address2>Suite 209</Address2>
<City>Eden Prairie</City>
<Region>MN</Region>
<Country>USA</Country>
<Postal_Code>55327</Postal_Code>
<E-mail>Wade@dhakabike.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>612-947-3344</Phone>
<Fax>612-947-6477</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>13</Customer_ID>
<Customer_Credit_ID>13</Customer_Credit_ID>
<Customer_Name>C-Gate Cycle Shoppe</Customer_Name>
<Contact_First_Name>Matthew</Contact_First_Name>
<Contact_Last_Name>Banks</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Owner</Contact_Position>
<Last_Years_Sales>29618.11</Last_Years_Sales>
<Address1>413 Robson Lane</Address1>
<Address2>Suite 1809</Address2>
<City>Winchester</City>
<Region>VA</Region>
<Country>USA</Country>
<Postal_Code>22618</Postal_Code>
<E-mail>Banks@barbadossports.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>540-662-7167</Phone>
<Fax>540-662-2730</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>14</Customer_ID>
<Customer_Credit_ID>14</Customer_Credit_ID>
<Customer_Name>Alley Cat Cycles</Customer_Name>
<Contact_First_Name>Rick</Contact_First_Name>
<Contact_Last_Name>Pratt</Contact_Last_Name>
<Contact_Title>Mr.</Contact_Title>
<Contact_Position>Owner</Contact_Position>
<Last_Years_Sales>298356.22</Last_Years_Sales>
<Address1>1842 St. Anne Place</Address1>
<Address2>Suite 618</Address2>
<City>Concord</City>
<Region>MA</Region>
<Country>USA</Country>
<Postal_Code>01733</Postal_Code>
<E-mail>Pratt@belgiumbike.com</E-mail>
<Web_Site>http://www.crystaldecisions.com</Web_Site>
<Phone>508-287-8535</Phone>
<Fax>508-28-73694</Fax>
</Customer_Query>
<Customer_Query>
<Customer_ID>15</Customer_ID>
<Customer_Credit_ID>15</Customer_Credit_ID>
<Customer_Name>The Bike Cellar</Customer_Name>
